services:
  - type: web
    name: eerip
    runtime: rust
    rootDir: backend
    buildCommand: |
      cargo install sqlx-cli &&
      cargo sqlx migrate run --source ./db/migrations &&
      cargo build --release
    startCommand: cargo run --release
    healthCheckPath: /healthz
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        value: sqlite://anonymous_messaging.db
